### ISSUE TITLE
Script of Scripts to mix MATLAB and python

### ISSUE THREAD

**Issue by matteomancini** [mtl-brainhack-school-2019/EEG_Connectivity_BrainHack_2019#3]
I have seen that you want to go from EEGLAB to MNE, if you have some of the files from EEGLAB that is not immediate for you to open with python, you may consider Script of Scripts:
https://vatlab.github.io/sos-docs/
I tried it once and it wasn't too complicated, basically it allows you to run multiple kernels in Jupyter and have a cell with code in MATLAB and the next with python code.
Some practical examples here:
https://qmrlab.org/blog.html

**Comment by anna-monnier** [comment]
Oh niiiiceee !! Thank you so much this will be really useful !
